### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by sercaneraslan**
Hello,

I ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

Thank you.

### CODE REVIEW

**Comment by paulhhowells** [comment]
+1 for updating to work with Grunt 1.0

**Comment by ryanburr** [comment]
+1. Would like to start using ng-docs with Grunt 1.0 ASAP

**Comment by m7r** [comment]
@sercaneraslan could you please rename the commit message to:
feat(): support Grunt 1.0

**Comment by sercaneraslan** [comment]
New Pull Request: https://github.com/m7r/grunt-ngdocs/pull/194

**Comment by m7r** [comment]
@sercaneraslan 0.2.10 is released now

**Comment by sercaneraslan** [comment]
Thank you @m7r

**Pull request closed without merging**
